### ISSUE TITLE
Crash upon entering

### ISSUE THREAD

**Issue by DanielByrneCS** [Rinnegatamante/ShaRKBR33D#1]
I have just set up sharkbr33d from the homebrew browser on my fat vita and I am using an sd2vita. Upon entering I get downloading sharkf00d then a crash 
![1666214095808384678811038686601](https://user-images.githubusercontent.com/24895341/196805796-db3e6d0d-b652-45a9-a8b7-716ef8e1bc01.jpg)

**Comment by Rinnegatamante** [comment]
Do you actually happen to have ux0:data folder and either ux0:tai/config.txt or ur0:tai/config.txt?

**Comment by DanielByrneCS** [comment]
> Do you actually happen to have ux0:data folder and either ux0:tai/config.txt or ur0:tai/config.txt?

I use ur0:tai for my config.txt and there is a folder called data in ux0

**Comment by fexofenadine** [comment]
I have the same error, right after it attempts to download PSM Runtime v.1.00

I have a ux0:data/, ur0:data/ and ur0:tai/config.txt

there is an old libshacccg.suprx file in ur0:data/ if that's relevant

**Comment by Rinnegatamante** [comment]
Pushed a fix for it: https://github.com/Rinnegatamante/ShaRKBR33D/releases/tag/v.1.0.1

**Comment by fexofenadine** [comment]
sorry I meant to write about this when you posted it: your fix has worked for me

thanks very much!
